# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.IntegerField(max_length=3)),
                ('deadline', models.DateField()),
                ('assignee', models.CharField(max_length=100)),
            ],
        ),
    ]
